name: GenerateSnake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:
  update-repository:
    name: Update Snake
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            ./img/snake.svg
            ./img/snake-dark.svg?palette=github-dark

      - name: Push to GitHub
        uses: EndBug/add-and-commit@main
        with:
          branch: main
          message: "Update snake"
          author_name: "github-actions[bot]"
          author_email: "41898282+github-actions[bot]@users.noreply.github.com"
